<?php

namespace App\Models;

use App\Notifications\TopicReplied;

class Reply extends Model
{
    protected $fillable = ['content','topic_id','user_id'];

    public function topic()
    {
        return $this->belongsTo(Topic::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        //需要防止xss攻击
        static::creating(function ($model) {
            $model->content = clean($model->content, 'user_topic_body');
        });

        static::created(function ($model) {
            $topic=$model->topic;
            //增加对应topic的评论数
            $topic->increment('reply_count', 1);

            //通知作者话题有新的回复
            $topic->user->replyNotify($model);
        });

        static::deleted(function ($model) {
            $topic = $model->topic;
            $topic->decrement('reply_count', 1);
        });
    }
}
